version: '3.1'

services:

  database:
    container_name: 'ab-events-database'
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'events-api'
      POSTGRES_PASSWORD: 'mudar123'
      POSTGRES_DB: 'ab_eventos'
    ports:
      - "5432:5432"

  cache:
    container_name: 'ab-events-cache'
    image: redis:7.0.12-alpine3.18
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    container_name: 'ab-events-backend'
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3333:3333"
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_started
